### ISSUE TITLE
[FeatureRequest] Letsencrypt ssl certificates

### ISSUE THREAD

**Issue by vicpara** [rkwaysltd/gke-infra#2]
I really like this project. The only missing feature required for a prod environment would be the let's encrypt certificate.
How difficult would be to integrate it in the cluster initial setup ?

**Comment by kupson** [comment]
Hi! It's still work in progress - once completed there will be two certificate managers running (with let's encrypt).
The dev and prod clusters should run on separate set of domains so the credentials will be different.

Plan for now:
- finish GH workflows so there will be two clusters dev and prod, deployed from `cluster/{dev,prod}` branches
- add documentation about setting let's encrypt certificate issuer
- add internal nginx-ingress as a intermediate layer so we can use just one stable GC-ingress and have multiple dynamic ingresses with our certs
- deploy service mesh

Once the project reaches that stage it will be ready for forking into destination account.

**Comment by vicpara** [comment]
I like the plan. Thanks for clarifying this. Looking forward to it.

**Comment by kupson** [comment]
GH actions should be ready, the branch names are `main` and `main-prod`.

Intended workflow:
- create new branch from `main`
- push commits and create PR
- terraform plan will be added as comment to PR (a feature stolen from Github Terraform action example)
- terraform will apply changes on merge/push to `main` 

Same with `main-prod` branch but most merge requests should be from `main` branch.

**Comment by kupson** [comment]
Let's Encrypt certificates added. Certificate manager is issuing certs based on `Certificate` objects or annotations in `Ingress` objects. There is a certificate for ingress RR record (by default it's wildcard certificate for a whole domain).

Closed in #12
