### ISSUE TITLE
Error: Failed to construct REST client

### ISSUE THREAD

**Issue by kupson** [rkwaysltd/gke-infra#4]
When running on a fresh GC projects:

```sh
$ ./scripts/terraform_local_dev.sh plan

Error: Failed to construct REST client

  on certman.tf line 46, in resource "kubernetes_manifest" "cert_manager_cf_issuer":
  46: resource "kubernetes_manifest" "cert_manager_cf_issuer" {

cannot create REST client: no client config
```

**Comment by kupson** [comment]
Proper fix would require better code structure/modularisation like in this example - https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/gke

Quick workaround - comment out `kubernetes_manifest` resource on first `plan/apply` run.

**Comment by vicpara** [comment]
I'll be trying to deploy a new prod cluster next week on Monday.  I'll go through the deployment steps and come back with feedback about the experience.

**Comment by kupson** [comment]
@vicpara 
After fixing some more bugs affecting local re-install I managed to test working workaround for the provider-dependency issue. It's added to README.md in c4f147750213e53c09d5a3c4d6f8aa562e4035c1.

**Comment by vicpara** [comment]
Awesome news. Thank you Rafal.

**Comment by kupson** [comment]
Fixed by introducing preflight mode (terraform_preflight variable). Looks like to solve this and similar issues it's either two-step run of single module or splitting the project into two root modules. There are additions to installation procedure in `README.md` file.
